controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
api_login_check:
  path: /api/login_check
api_signup:
  path: /api/signup
  controller: App\Controller\SecurityController
  methods: [GET]
assign_order_to_employee:
  path: /assign/order/{orderId}/employee/{employeeId}
  controller: App\Controller\OrderController::assignOrderToEmployee
